name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-18.04
    services:
      postgrescon:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: yash
          POSTGRES_PASSWORD: yash123

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run API
        run: go build -o restapi && ./restapi
        env:
          DBHOST: postgrescon
          DBPORT: 5432
          DBUSER: yash
          DBPASS: yash123
          DBNAME: yash
      - name: Run Tests
        run: go test
